-keep class org.apache.ftpserver.**{ *;}
-keep class org.apache.mina.**{ *;}
-keep class org.slf4j.**{ *;}
-dontwarn org.apache.ftpserver.**
-dontwarn org.apache.mina.**
-dontwarn org.slf4j.**
-dontnote org.apache.ftpserver.**
-dontnote org.apache.mina.**
-dontnote org.slf4j.**